# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: test1

steps:
- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
  displayName: 'Use Terraform latest'

steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
  displayName: 'Terraform : azurerm'
  inputs:
    commandOptions: '-reconfigure'
    backendServiceArm: devopsconn
    backendAzureRmResourceGroupName: 'rg-tfstate'
    backendAzureRmStorageAccountName: tfmsf
    backendAzureRmContainerName: tfstate
    backendAzureRmKey: terraform.tfstate